---
local_interface:
 - name: Loopback1
   desc: Ansible created Loopback1
   ip_address: 172.16.20.1
   prefix: 32
   area: 0
 - name: Loopback2
   desc: Ansible created Loopback2
   ip_address: 172.16.20.11
   prefix: 32
   area: 0
local_interfaceE:
 - name: Ethernet1/2
   desc: vers Nexus 3
   ip_address: 10.10.23.2
   prefix: 30
   area: 0
 - name: Ethernet1/3
   desc: vers Nexus 1
   ip_address: 10.10.12.2
   prefix: 30
   area: 0
